### ISSUE TITLE
Deploy Production to covid19app.who.int

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1298]
Open issues:
- [x] covid19app.who.int subdomain (depends on https://github.com/WorldHealthOrganization/app/issues/649)
- [x] subpath for our RPCs / trampoline link?
- [x] TOS and PN - https://github.com/WorldHealthOrganization/app/issues/1510

Other:
- [x] Endpoint Security - https://github.com/WorldHealthOrganization/app/issues/1508

Terraform Setup:
- [x] App Engine and Firebase - https://github.com/WorldHealthOrganization/app/issues/1555
- [x] Network Security - https://github.com/WorldHealthOrganization/app/issues/649
- [x] Cloud Storage (static content) - https://github.com/WorldHealthOrganization/app/issues/1624
- [x] Cloud Logs - https://github.com/WorldHealthOrganization/app/issues/1625
- [x] Terraform validation (optional) - https://github.com/WorldHealthOrganization/app/issues/1620

**Comment by advayDev1** [comment]
@crazybob How would we handle cookie pollution from a security perspective?  We don't want our appengine to be able to set cookies on their pages, nor vice-versa yes?

**Comment by crazybob** [comment]
My plan is to map the following domains:

app.who.int (production)
staging.who.int (staging copy of production)
hackerone.who.int (just like production, for hackers to attack)

We could use separate domains, but we don't rely on cookies, and we don't host user-provided content, so I don't think it's worth the added complexity. Even if we start using cookies in the future, we could simply ignore cookies from .who.int. Happy to have a meeting to discuss.

**Comment by crazybob** [comment]
That said, if/when we add an admin interface, we should probably add additional domains:

admin.app.who.int
etc.

This will prevent the user-facing app from calling admin RPCs.

**Comment by advayDev1** [comment]
@crazybob last time we moved domains we kept staging and h1 not on the main domain.

think we should move ONLY prod to who.int.

no unapproved code should run on who's domains

```
  static final String STAGING = 'https://staging.whocoronavirus.org';
  static final String PROD = 'https://app.who.int';
```

**Comment by marcmcl** [comment]
@crazybob  - could we make sure we remember to disable TLS 1.0 and 1.1.

**Comment by advayDev1** [comment]
Since we'll be deploying all commits to staging automatically ( https://github.com/WorldHealthOrganization/app/pull/1401 ) if we do end up doing this, only production should be on who.int and all non-production services should be on lesser domains.

**Comment by advayDev1** [comment]
Bruno, can we get:
https://myhealth.who.int/ just for production.

Non-prod should not be on who.int for security

**Comment by brunobowden** [comment]
@advayDev1 - working on this. Can I ask what the "subpath for our RPCs / trampoline link" covers? My understanding is that we'll get a subdomain, so that means our url paths should just work automatically. Is the trampoline link for the app store redirect, e.g. http://staging.whocoronavirus.org/app?

**Comment by advayDev1** [comment]
@brunobowden the point was to route only a subpath of the subdomain to the appengines.  this future proofs the ability for WHO to host a marketing site on the main domain, and also for WHO/this project to push a CMS or other admin console to a different subpath.

**Comment by brunobowden** [comment]
App Engine and Static Content has been deployed to production. Client still needs to be updated to use - #1768... but I consider this closed.
