### ISSUE TITLE
Result card missing link for "protect yourself" in Symptom Check Up

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1407]
Symptom Checker result card shows "Learn other ways to protect others >" which suggests it should be a link but nothing is shown. The yaml has the entry "href: /protect-yourself" but no link. Let me know if I should file this as a bug.

```
      id: protect_others
      title: >-
        Learn other ways to protect others ›
      href: /protect-yourself
```

Href in source code:
https://github.com/WorldHealthOrganization/app/blob/190cb41cf4116ff10d4c59fb93d7ee19cfbbd842/client/flutter/assets/content_bundles/symptom_checker.en.yaml#L228

**Describe the problem**
Suggestive of link but no link shown

**To Reproduce**

1. Use Symptom Check-In tool
2. No emergency symptoms
3. Symptoms: Fever only
4. Close contact: Not that I know of
5. Long Term Facility: No
6. Age: Under 60
7. Pre-existing conditions: No

**Expected, correct behavior**
A link is shown that takes the user to the "Protect Yourself" view

**Phone/Tablet (please complete the following information):**

- Device: iPhone 11 Pro Max
- OS: 13.5
- App Version: 0.11.1

**Screenshots**

<details>
<summary>Screenshots</summary>
![727](https://user-images.githubusercontent.com/679339/87125303-1e948700-c23f-11ea-990f-59e2ff93844c.jpg)

</details>

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by brunobowden** [comment]
FYI @advayDev1 @hspinks

**Comment by brunobowden** [comment]
Removed from client
