### ISSUE TITLE
Decisions to be made

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#19]
Starting an ongoing thread for the architecture decisions that we should make & have made as a reference. Writing this out in a quick brain dump, so leave a comment with decisions that are missing. Goal should be to make these decisions quickly and not look back once made. Will continue to update this as the discussions/decisions progress.

* [x] Client Framework - **Decision: Ionic React for v0.1** 
  * _Note: may move to React Native for 0.1+_
* [x] Language - **Decision: TypeScript per #7** 
* [x] Server - **Decision: Google App Engine + Github Pages**
* [ ] Initial Client Scaffolding
  * See #33 
* [ ] CI
  * See #12 
* [ ] State Management Library
  * Whether we want to use one, or whether Firebase will serve our purposes well enough
* [ ] Routing / Navigation Library
* [ ] Code Style
  * Whether we want to try to standardize this now with linters and/or Prettier, or whether that's a future us problem
  * See #30 
* [ ] Tests
  * Whether test coverage is a requirement, or whether that's a future us problem due to tight time constraints
* [ ] Git / Workflow Standards
  * How strictly we want to use standard git flows, whether or not we want to implement standardized commit messages (e.g. something like [AngularJS's guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#)), etc
* [ ] Device Support
  * See #13 
* [ ] Automatic Security Enforcement
  * Snyk.io, GitHub's built-in, both, others?
* [ ] Dependency updates
  * Dependabot/GitHub, others?
* [ ] Dependency / Build Management
  * Initial React Native scaffolding uses Gradle for Android, CocoaPods for iOS
  * Currently using yarn for JS dependencies, but should decide yarn vs npm
* [ ] Localization & Internationalization Strategies/Library
  * Proposed in #21: [`jquery.i18n`](https://github.com/wikimedia/jquery.i18n) (PWA), [`react-native-localize`](https://github.com/react-native-community/react-native-localize) (React Native), [`react-i18next`](https://github.com/i18next/react-i18next) (PWA), [`react-intl`](https://github.com/formatjs/react-intl) (PWA)
* [ ] Strategy for Dynamic & Offline Content Delivery
  * See #24 

...what else?

**Comment by advayDev1** [comment]
- [ ] Automatic security enforcement
  - Snyk.io, GitHub's built-in, both, others?
- [ ] Dependency updates
  - Dependabot/GitHub, others?

**Comment by advayDev1** [comment]
- [ ] Dependency/build management
  - ReactNative scaffolding uses Gradle for Android, CocoaPods for iOS
  - Need to decide npm vs yarn for the React code itself (initial check in uses yarn)

**Comment by myire** [comment]
responded in:
https://github.com/WorldHealthOrganization/app/issues/7

Plain old javascript is going to let us work together as fast as possible.  We can refine over time.

Choosing a back end/front end optimized for high throughput data streaming applications without considering privacy implications and the requirements in:

https://docs.google.com/document/d/1isNMLpwI2iUY92KPwJHfY7kQnpN3oCuUl6c94J7Qmhs/edit#heading=h.u7xtg8lt787c

is a poor choice, IMHO.

Specifically:

> **Essential Features**

> Small app size and bandwidth usage so that it can be used throughout the world
> Offline for low connectivity environments with reporting when connectivity returns
> Localization of interface to practically every language in common use
> Separation of data to the server, allowing customization for local areas

> **Not Featured**

> Healthcare direct contact, e.g. video chat. Best provided by existing services (can link to available telehealth services)
> News / global dashboard, distraction from purprose, provided elsewhere
> Healthcare reporting system. There’s already a well-established reporting system in developed countries that we should respect. This calculus may change in less developed healthcare systems

**Comment by advayDev1** [comment]
- [ ] Localization and globalization #21

**Comment by advayDev1** [comment]
- [ ] Dynamic/offline delivery design #24

**Comment by hspinks** [comment]
updated per this morning's call:
* Client Framework: Using PWA in native wrapper, specifically [Ionic React](https://ionicframework.com/docs/react/quickstart)
* Server: Using Google App Engine with Github Pages

**Comment by RohanTalip** [comment]
>   * Need to decide npm vs yarn for the React code itself (initial check in uses yarn)

It looks like npm has been chosen over yarn, at least implicitly, since the onboarding instructions mention npm (and not yarn) and app/client/ionic/package.json has scripts that use npm (and not yarn).

I'm just curious what the rationale was though? (FYI, I'm OK with this)

**Comment by myiremark** [comment]
Can I close this @advayDev1 @hspinks
