### ISSUE TITLE
Make sure the following tracking identifiers in Analytics are disabled

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#671]
https://firebase.google.com/docs/analytics/configure-data-collection?platform=ios

- [ ] iOS - disable IDFA (Advertising Identifier)
- [ ] iOS - disable Disable personalized advertising features
- [x] iOS - Temporarily disable collection at startup
- [ ] Android - Disable Advertising ID collection
- [ ] Android - Disable personalized advertising features
- [x] Android - Temporarily disable collection at startup
- [ ] iOS - disable IDFV (Identifier for Vendor)
- [ ] Android - disable collection of SSAID (Settings.Secure.ANDROID_ID)

**Comment by myiremark** [comment]
> https://firebase.google.com/docs/analytics/configure-data-collection?platform=ios
> 
>     * []  iOS - disable IDFA (Advertising Identifier) (unconfirmed)
>     * [x]  iOS - disable Disable personalized advertising features
>     * [x]  iOS - Temporarily disable collection at startup
>     * [x]  Android - Disable Advertising ID collection
>     * [x]  Android - Disable personalized advertising features
>     * [x]  Android - Temporarily disable collection at startup
>     * [x]  iOS - disable IDFV (Identifier for Vendor)
>     * [x]  Android - disable collection of SSAID (Settings.Secure.ANDROID_ID)
